version: '3.7'
services:
  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2.6-r1-g0a3336c
    container_name: ${PG_VIRTUOSO_CONTAINER_NAME:-pg_virtuoso}
    networks:
      - pgnet 
    ports:
      - 28890:8890
    environment:
      DBA_PASSWORD: "dba"
      VIRT_Parameters_NumberOfBuffers: "680000"
      VIRT_Parameters_MaxDirtyBuffers: "500000"
      VIRT_Client_SQL_PREFETCH_ROWS: "10000"
      VIRT_Client_SQL_PREFETCH_BYTES: "160000"
      VIRT_SPARQL_ResultSetMaxRows: "1000000"
      VIRT_SPARQL_MaxSortedTopRows: "1000000"
      VIRT_SPARQL_MaxQueryExecutionTime: "300"
      VIRT_SPARQL_MaxQueryCostEstimationTime: "-1"
    user: ${UID:-0}:${GID:-0}
    volumes:
      - ${PWD}/config/virtuoso:/settings
      - ${PWD}/data/virtuoso:/database
    restart: always
networks:
  pgnet:
    external:
      name: pgnet
